name: CI-Workflow

on:
  push:
    branches:
      - main

env:
  ENV_NAME: ci1

jobs:
  call-workflow:
    uses: chrisowen491/ReusableActions/.github/workflows/build_deploy_test_lambda_via_sam.yaml@main
    with:
      env: ci1
      stack_name: ResultsSearch-ci1
      base_url: https://api.ci1.tranmere-web.com/result-search/
    secrets: inherit          